name: Update Podcasts

on:
  schedule:
    - cron: '0 4 * * *' # Tous les jours Ã  04h00 UTC
  workflow_dispatch:    # Permet de lancer manuellement via un bouton

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install FFmpeg & Libraries
      run: |
        sudo apt-get install -y ffmpeg
        pip install -r requirements.txt
        
    - name: Run Generator Script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python podcast_gen.py
      
    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Podcast Bot'
        git config --global user.email 'bot@noreply.github.com'
        # On ajoute TOUS les fichiers XML (*.xml) et le log
        git add *.xml downloaded_log.txt
        # On commit seulement s'il y a du nouveau
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feeds" && git push)
